//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvicitiDBEntities : DbContext
    {
        public EvicitiDBEntities()
            : base("name=EvicitiDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accesorios> Accesorios { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<Coleccionables> Coleccionables { get; set; }
        public virtual DbSet<Consolas> Consolas { get; set; }
        public virtual DbSet<Detalle_Ventas> Detalle_Ventas { get; set; }
        public virtual DbSet<Extras> Extras { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Juegos> Juegos { get; set; }
        public virtual DbSet<PermisosServidores> PermisosServidores { get; set; }
        public virtual DbSet<Servidores> Servidores { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Ventas> Ventas { get; set; }
    }
}
