//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermisosServidores
    {
        public int ID_Permiso { get; set; }
        public int ID_Servidor { get; set; }
        public int ID_Usuario { get; set; }
        public string UsuarioAcceso { get; set; }
        public string ContrasenaAcceso { get; set; }
    
        public virtual Servidores Servidores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
